### ISSUE TITLE
[ERROR] Bad Request

### ISSUE THREAD

**Issue by Pancakes0** [Glagan/SyncDex#46] opened 2021-02-24 13:12 UTC
**Describe the bug**
i dont know how. i was reading in the morning, past a few chapters already. then when i clicked next chapter this happened. its midnight now and still does it. i tried to go to anilist and it was fine. i dunno. though when i was reading another manga. kemono giga. this happened and i re-entered the id then it works? up until now. dunno what happened.

**Screenshots**
![Screen Shot 2021-02-24 at 9 01 24 PM](https://user-images.githubusercontent.com/73923883/109004851-3e03f580-76e4-11eb-9bb3-347248ff9361.png)

**Browser**
**Firefox 85.0.2 (64-bit)**

**Options and logs** 
```
{"logs":[{"d":1610285142565,"msg":"Error on request [https://myanimelist.net/about.php]: TypeError: NetworkError when attempting to fetch resource."},{"d":1610285144039,"msg":"Error on request [https://graphql.anilist.co]: TypeError: NetworkError when attempting to fetch resource."},{"d":1610285145126,"msg":"Error on request [https://mangadex.org/api/v2/user/me]: TypeError: NetworkError when attempting to fetch resource."}
```
```
216 | 2/19/2021, 22:08:00 | Error on request [https://graphql.anilist.co]: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
-- | -- | --
215 | 2/19/2021, 22:07:13 | Error on request [https://graphql.anilist.co]: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
214 | 2/19/2021, 22:07:04 | Error on request [https://graphql.anilist.co]: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

**Additional context**

tnx

**Comment by Glagan** [comment] 2021-02-24 15:24
Hi, please *read* and follow the **Bug Report** template when you open an issue.  
Could you send me your actual options and logs, as written in the template, you can access it in the options, on the bottom left: 
![image](https://user-images.githubusercontent.com/8447621/109022319-fff2db80-76bb-11eb-883c-ff381b88e382.png)  
and then you can directly copy/paste it between a double `` ` `` characters.  

The error might just have been a temporary server error from you or **Anilist** and I can't reproduce it with the title you mentionned (Kemono Giga).  
This might also have been a rate limit, but I should prevent that already, did you open a lot of chapters or changed chapters quickly, or was there an Import in the background ?

**Comment by Glagan** [comment] 2021-03-09 23:09
This was related to the Anilist API rate limit, which was for some reasons being reduced by 4 or more per requests and was not being reset, which triggered the limit easily.  
I don't know why, maybe it's expected if they have a lot of traffic ?

I now look at the ``X-RateLimit-*`` headers and sleep if we're close to the limit or reached it.

It will be in the next release (``0.3.0``) but I'm not sure when I will publish it, there was a lot of changes and I need to do some more tests.

**Comment by Pancakes0** [comment] 2021-03-12 13:43
Okay, thank you! 
i just saw this, if its not late ~~probably is~~ here,
```
{"logs":[{"d":1610457731586,"msg":"Anilist::get ~ Execution time: 2281ms"},{"d":1610457740091,"msg":"Anilist::get ~ Execution time: 3076ms"},{"d":1610457744672,"msg":"MyAnimeList::get ~ Execution time: 3586ms"},{"d":1610457745103,"msg":"Anilist::get ~ Execution time: 4026ms"},{"d":1610457750568,"msg":"Anilist::get ~ Execution time: 2607ms"},{"d":1610457751198,"msg":"MyAnimeList::get ~ Execution time: 3245ms"},{"d":1610457753961,"msg":"MyAnimeList::get ~ Execution time: 1853ms"},{"d":1610457755012,"msg":"Anilist::get ~ Execution time: 2905ms"},{"d":1610457773362,"msg":"MyAnimeList::get ~ Execution time: 977ms"},{"d":1610457774431,"msg":"Anilist::get ~ Execution time: 2048ms"},{"d":1610457780098,"msg":"MyAnimeList::get ~ Execution time: 4094ms"},{"d":1610457781479,"msg":"Anilist::get ~ Execution time: 5477ms"},{"d":1610457787496,"msg":"MyAnimeList::get ~ Execution time: 893ms"},{"d":1610457788468,"msg":"Anilist::get ~ Execution time: 1866ms"},{"d":1610457843690,"msg":"Anilist::get ~ Execution time: 662ms"},{"d":1610457874144,"msg":"Anilist::get ~ Execution time: 883ms"},{"d":1610458679095,"msg":"MyAnimeList::get ~ Execution time: 2023ms"},{"d":1610458679800,"msg":"Anilist::get ~ Execution time: 2728ms"},{"d":1610458732492,"msg":"MyAnimeList::get ~ Execution time: 1623ms"},{"d":1610458732890,"msg":"Anilist::get ~ Execution time: 2029ms"},{"d":1610458992060,"msg":"Anilist::get ~ Execution time: 2857ms"},{"d":1610458992203,"msg":"MyAnimeList::get ~ Execution time: 3004ms"},{"d":1610459015293,"msg":"MyAnimeList::get ~ Execution time: 590ms"},{"d":1610459016729,"msg":"Anilist::get ~ Execution time: 2028ms"},{"d":1610459022550,"msg":"MyAnimeList::get ~ Execution time: 4335ms"},{"d":1610459023520,"msg":"Anilist::get ~ Execution time: 5313ms"},{"d":1610499269065,"msg":"MyAnimeList::get ~ Execution time: 1016ms"},{"d":1610499270391,"msg":"Anilist::get ~ Execution time: 2347ms"},{"d":1610501675370,"msg":"Anilist::get ~ Execution time: 3069ms"},{"d":1610501675446,"msg":"MyAnimeList::get ~ Execution time: 3149ms"},{"d":1610501681467,"msg":"Anilist::get ~ Execution time: 5213ms"},{"d":1610501682717,"msg":"MyAnimeList::get ~ Execution time: 5132ms"},{"d":1610501684785,"msg":"Anilist::get ~ Execution time: 7204ms"},{"d":1610501715189,"msg":"MyAnimeList::get ~ Execution time: 1196ms"},{"d":1610501716121,"msg":"Anilist::get ~ Execution time: 2131ms"},{"d":1610501759721,"msg":"MyAnimeList::get ~ Execution time: 952ms"},{"d":1610501761101,"msg":"Anilist::get ~ Execution time: 2333ms"},{"d":1610501780965,"msg":"Anilist::get ~ Execution time: 968ms"},{"d":1610503218064,"msg":"MyAnimeList::get ~ Execution time: 2027ms"},{"d":1610503219075,"msg":"Anilist::get ~ Execution time: 3039ms"},{"d":1610506192925,"msg":"MyAnimeList::get ~ Execution time: 982ms"},{"d":1610506194071,"msg":"Anilist::get ~ Execution time: 2128ms"},{"d":1610506263876,"msg":"MyAnimeList::get ~ Execution time: 993ms"},{"d":1610506265229,"msg":"Anilist::get ~ Execution time: 2347ms"},{"d":1610506276015,"msg":"MyAnimeList::get ~ Execution time: 2040ms"},{"d":1610506276415,"msg":"Anilist::get ~ Execution time: 2445ms"},{"d":1610506277866,"msg":"Anilist::get ~ Execution time: 2550ms"},{"d":1610506303984,"msg":"Anilist::get ~ Execution time: 690ms"},{"d":1610506312021,"msg":"MyAnimeList::get ~ Execution time: 1611ms"},{"d":1610506313053,"msg":"Anilist::get ~ Execution time: 2647ms"},{"d":1610506320848,"msg":"MyAnimeList::get ~ Execution time: 992ms"},{"d":1610506321863,"msg":"Anilist::get ~ Execution time: 2010ms"},{"d":1610506417128,"msg":"MyAnimeList::get ~ Execution time: 940ms"},{"d":1610506418422,"msg":"Anilist::get ~ Execution time: 2237ms"},{"d":1610543705753,"msg":"MyAnimeList::get ~ Execution time: 993ms"},{"d":1610543707402,"msg":"Anilist::get ~ Execution time: 2642ms"},{"d":1610543892399,"msg":"MyAnimeList::get ~ Execution time: 814ms"},{"d":1610543894131,"msg":"Anilist::get ~ Execution time: 2548ms"},{"d":1610544538375,"msg":"MyAnimeList::get ~ Execution time: 672ms"},{"d":1610544539996,"msg":"Anilist::get ~ Execution time: 2295ms"},{"d":1610544665506,"msg":"MyAnimeList::get ~ Execution time: 809ms"},{"d":1610544666671,"msg":"Anilist::get ~ Execution time: 1977ms"},{"d":1610545009180,"msg":"Anilist::get ~ Execution time: 1288ms"},{"d":1610545018419,"msg":"Anilist::get ~ Execution time: 1050ms"},{"d":1610586415947,"msg":"Anilist::get ~ Execution time: 3497ms"},{"d":1610586416362,"msg":"MyAnimeList::get ~ Execution time: 3916ms"},{"d":1610586416673,"msg":"MyAnimeList::get ~ Execution time: 3520ms"},{"d":1610586417874,"msg":"Anilist::get ~ Execution time: 4720ms"},{"d":1610586422425,"msg":"MyAnimeList::get ~ Execution time: 1455ms"},{"d":1610586423497,"msg":"Anilist::get ~ Execution time: 2531ms"},{"d":1610586427715,"msg":"MyAnimeList::get ~ Execution time: 1999ms"},{"d":1610586428203,"msg":"Anilist::get ~ Execution time: 2530ms"},{"d":1610630266603,"msg":"Updating from version 0.2.0 to 0.2.1"},{"d":1610630266610,"msg":"Applied patch version 0.2.0.1"},{"d":1610716752285,"msg":"Updating from version 0.2.1 to 0.2.2"},{"d":1611026916290,"msg":"Updating from version 0.2.2 to 0.2.3"},{"d":1611026928591,"msg":"Found MangaDex max Chapter undefined"},{"d":1611026929660,"msg":"Volume reset chapters ? false"},{"d":1611026975401,"msg":"Found MangaDex max Chapter undefined"},{"d":1611026976384,"msg":"Volume reset chapters ? false"},{"d":1611026991384,"msg":"Found MangaDex max Chapter undefined"},{"d":1611026992442,"msg":"Volume reset chapters ? false"},{"d":1611026994565,"msg":"Found MangaDex max Chapter undefined"},{"d":1611026995297,"msg":"Volume reset chapters ? false"},{"d":1611027006677,"msg":"Found MangaDex max Chapter undefined"},{"d":1611027007676,"msg":"Volume reset chapters ? false"},{"d":1611027026540,"msg":"Found MangaDex max Vol. 2 Ch. undefined"},{"d":1611027027496,"msg":"Volume reset chapters ? false"},{"d":1611027028325,"msg":"Found MangaDex max Chapter undefined"},{"d":1611027031097,"msg":"Volume reset chapters ? false"},{"d":1611027031643,"msg":"Found MangaDex max Chapter undefined"},{"d":1611027032467,"msg":"Volume reset chapters ? false"},{"d":1611027036292,"msg":"Found MangaDex max Chapter undefined"},{"d":1611027036872,"msg":"Volume reset chapters ? false"},{"d":1611027066435,"msg":"Found MangaDex max Chapter undefined"},{"d":1611027067410,"msg":"Volume reset chapters ? false"},{"d":1611027079891,"msg":"Found MangaDex max Chapter undefined"},{"d":1611027080835,"msg":"Volume reset chapters ? false"},{"d":1611027088585,"msg":"Volume reset chapters ? false"},{"d":1611027103594,"msg":"Volume reset chapters ? false"},{"d":1611027109384,"msg":"Found MangaDex max Chapter undefined"},{"d":1611027110053,"msg":"Volume reset chapters ? false"},{"d":1611027112685,"msg":"Found MangaDex max Chapter undefined"},{"d":1611027112960,"msg":"Volume reset chapters ? false"},{"d":1611027143018,"msg":"Volume reset chapters ? false"},{"d":1611027200568,"msg":"Found MangaDex max Chapter undefined"},{"d":1611027201250,"msg":"Volume reset chapters ? false"},{"d":1611027206911,"msg":"Volume reset chapters ? false"},{"d":1611027210416,"msg":"Volume reset chapters ? false"},{"d":1611027220261,"msg":"Volume reset chapters ? false"},{"d":1611027244653,"msg":"Volume reset chapters ? false"},{"d":1611027266511,"msg":"Volume reset chapters ? false"},{"d":1611111158595,"msg":"Volume reset chapters ? false"},{"d":1611111740799,"msg":"Found MangaDex max Chapter undefined"},{"d":1611111744497,"msg":"Volume reset chapters ? false"},{"d":1611113377708,"msg":"Found MangaDex max Vol. 2 Ch. undefined"},{"d":1611113380254,"msg":"Volume reset chapters ? false"},{"d":1611113388569,"msg":"Volume reset chapters ? false"},{"d":1611113394008,"msg":"Found MangaDex max Chapter undefined"},{"d":1611113396042,"msg":"Volume reset chapters ? false"},{"d":1611113422411,"msg":"Found MangaDex max Chapter undefined"},{"d":1611113424458,"msg":"Volume reset chapters ? false"},{"d":1611113428437,"msg":"Found MangaDex max Chapter undefined"},{"d":1611113431585,"msg":"Volume reset chapters ? false"},{"d":1611113440067,"msg":"Volume reset chapters ? false"},{"d":1611113443400,"msg":"Volume reset chapters ? false"},{"d":1611113797836,"msg":"Found MangaDex max Chapter undefined"},{"d":1611113800292,"msg":"Volume reset chapters ? false"},{"d":1611113806449,"msg":"Found MangaDex max Chapter undefined"},{"d":1611113808216,"msg":"Found MangaDex max Chapter undefined"},{"d":1611113809371,"msg":"Volume reset chapters ? false"},{"d":1611113811339,"msg":"Found MangaDex max Chapter undefined"},{"d":1611113815723,"msg":"Volume reset chapters ? false"},{"d":1611113846067,"msg":"Volume reset chapters ? false"},{"d":1611113853277,"msg":"Volume reset chapters ? false"},{"d":1611113986984,"msg":"Volume reset chapters ? false"},{"d":1611113990922,"msg":"Volume reset chapters ? false"},{"d":1611114849826,"msg":"Found MangaDex max Chapter undefined"},{"d":1611117045139,"msg":"Found MangaDex max Chapter undefined"},{"d":1611117047011,"msg":"Volume reset chapters ? false"},{"d":1611145830420,"msg":"Volume reset chapters ? false"},{"d":1611146012979,"msg":"Volume reset chapters ? false"},{"d":1611146021370,"msg":"Volume reset chapters ? false"},{"d":1611146030772,"msg":"Found MangaDex max Chapter undefined"},{"d":1611146031478,"msg":"Volume reset chapters ? false"},{"d":1611146061534,"msg":"Volume reset chapters ? false"},{"d":1611146065934,"msg":"Volume reset chapters ? false"},{"d":1611147116891,"msg":"Found MangaDex max Chapter undefined"},{"d":1611147118446,"msg":"Volume reset chapters ? false"},{"d":1611147283981,"msg":"Found MangaDex max Chapter undefined"},{"d":1611147284971,"msg":"Volume reset chapters ? false"},{"d":1611147683209,"msg":"Found MangaDex max Chapter undefined"},{"d":1611147684540,"msg":"Volume reset chapters ? false"},{"d":1611149323212,"msg":"Found MangaDex max Chapter undefined"},{"d":1611149324582,"msg":"Volume reset chapters ? false"},{"d":1611149743518,"msg":"Found MangaDex max Chapter undefined"},{"d":1611150096347,"msg":"Found MangaDex max Chapter undefined"},{"d":1611150097301,"msg":"Volume reset chapters ? false"},{"d":1611150716614,"msg":"Found MangaDex max Chapter undefined"},{"d":1611235909759,"msg":"Found MangaDex max Chapter undefined"},{"d":1611235910755,"msg":"Found MangaDex max Chapter undefined"},{"d":1611235916033,"msg":"Found MangaDex max Chapter undefined"},{"d":1611235916921,"msg":"Volume reset chapters ? false"},{"d":1611235930242,"msg":"Volume reset chapters ? false"},{"d":1611235949226,"msg":"Volume reset chapters ? false"},{"d":1611236150658,"msg":"Volume reset chapters ? false"},{"d":1611236730662,"msg":"Found MangaDex max Chapter undefined"},{"d":1611236733180,"msg":"Volume reset chapters ? false"},{"d":1611236753175,"msg":"Found MangaDex max Chapter undefined"},{"d":1611236754976,"msg":"Volume reset chapters ? false"},{"d":1611316559861,"msg":"Found MangaDex max Chapter undefined"},{"d":1611316564183,"msg":"Found MangaDex max Chapter undefined"},{"d":1611316565185,"msg":"Volume reset chapters ? false"},{"d":1611316572343,"msg":"Volume reset chapters ? false"},{"d":1611316598045,"msg":"Volume reset chapters ? false"},{"d":1611316696486,"msg":"Found MangaDex max Chapter undefined"},{"d":1611316706601,"msg":"Volume reset chapters ? false"},{"d":1611319596881,"msg":"Found MangaDex max Chapter undefined"},{"d":1611319652748,"msg":"Found MangaDex max Chapter undefined"},{"d":1611319655043,"msg":"Volume reset chapters ? false"},{"d":1611320105096,"msg":"Found MangaDex max Chapter undefined"},{"d":1611320107635,"msg":"Volume reset chapters ? false"},{"d":1611320115880,"msg":"Volume reset chapters ? false"},{"d":1611321205646,"msg":"Found MangaDex max Chapter undefined"},{"d":1611321209552,"msg":"Volume reset chapters ? false"},{"d":1611323728981,"msg":"Found MangaDex max Chapter undefined"},{"d":1611323761832,"msg":"Found MangaDex max Chapter undefined"},{"d":1611323764626,"msg":"Volume reset chapters ? false"},{"d":1611323767356,"msg":"Found MangaDex max Chapter undefined"},{"d":1611323768418,"msg":"Volume reset chapters ? false"},{"d":1611323769787,"msg":"Found MangaDex max Chapter undefined"},{"d":1611323770992,"msg":"Volume reset chapters ? false"},{"d":1611323790492,"msg":"Volume reset chapters ? false"},{"d":1611373897755,"msg":"Volume reset chapters ? false"},{"d":1611490393341,"msg":"Updating from version 0.2.3 to 0.2.4"},{"d":1611581016529,"msg":"Updating from version 0.2.4 to 0.2.5"},{"d":1611750616243,"msg":"Error on request [https://myanimelist.net/ownlist/manga/115495/edit?hideLayout]: TypeError: NetworkError when attempting to fetch resource."},{"d":1611750617830,"msg":"Error on request [https://graphql.anilist.co]: TypeError: NetworkError when attempting to fetch resource."},{"d":1611753937342,"msg":"Updating from version 0.2.5 to 0.2.6"},{"d":1611840629965,"msg":"Updating from version 0.2.6 to 0.2.7"},{"d":1612013810620,"msg":"Updating from version 0.2.7 to 0.2.8"},{"d":1612138983268,"msg":"Updated from version 0.2.8 to 0.2.11"},{"d":1612441393278,"msg":"Installation version 0.2.11"},{"d":1612701834225,"msg":"Installation version 0.2.11"},{"d":1612921379987,"msg":"Updated from version 0.2.11 to 0.2.12"},{"d":1612966207701,"msg":"Installation version 0.2.12"},{"d":1613743624971,"msg":"Error on request [https://graphql.anilist.co]: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data"},{"d":1613743633524,"msg":"Error on request [https://graphql.anilist.co]: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data"},{"d":1613743680149,"msg":"Error on request [https://graphql.anilist.co]: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data"},{"d":1614173057787,"msg":"Error on request [https://mangadex.org/api/v2/user/me]: TypeError: NetworkError when attempting to fetch resource."},{"d":1614173058013,"msg":"Error on request [https://graphql.anilist.co]: TypeError: NetworkError when attempting to fetch resource."},{"d":1614221865253,"msg":"Updated from version 0.2.12 to 0.2.14"},{"d":1614307315321,"msg":"Updated from version 0.2.14 to 0.2.15"},{"d":1614311564991,"msg":"Installation version 0.2.15"},{"d":1615118957310,"msg":"Error on request [https://graphql.anilist.co]: TypeError: NetworkError when attempting to fetch resource."},{"d":1615556222288,"msg":"Updated from version 0.2.15 to 0.3.0"}],"options":{"hideHigher":false,"hideLower":true,"hideLast":false,"highlight":true,"groupTitlesInLists":true,"thumbnail":true,"originalThumbnail":false,"progressInThumbnail":true,"thumbnailMaxHeight":80,"separateLanguages":true,"favoriteLanguage":"all","saveOpenedChapters":true,"chaptersSaved":100,"saveOnlyHigher":true,"saveOnlyNext":false,"confirmChapter":true,"updateOnlyInList":false,"iconsSilentAfterSync":true,"saveOnLastPage":false,"linkToServices":true,"overviewMainOnly":true,"mdUpdateSyncDex":false,"biggerHistory":false,"chapterStatus":false,"notifications":true,"errorNotifications":true,"errorDuration":4000,"infoDuration":4000,"successDuration":4000,"useMochi":true,"acceptLowScore":false,"updateMD":false,"updateMDProgress":false,"checkOnStartup":false,"checkOnStartupMainOnly":true,"checkOnStartupCooldown":30,"silentUpdate":false,"logLevel":0,"services":["mal","al"],"noReloadStatus":true,"tokens":{"anilistToken":"set"},"colors":{"highlights":["rgba(28, 135, 141, 0.8)","rgba(22, 65, 87, 0.8)","rgba(28, 103, 141, 0.8)"],"nextChapter":"rgba(199, 146, 2, 0.4)","higherChapter":"transparent","lowerChapter":"rgba(180, 102, 75, 0.4)","openedChapter":"rgba(28, 135, 141, 0.4)"},"version":0.3,"subVersion":0,"autoSync":true,"mainService":"mal"}}
```

**Closed as completed** 2021-03-12 13:43 UTC
Labels: bug

**Comment by Glagan** [comment] 2021-03-12 13:50
Thanks for the logs, I see you're already on ``0.3.0`` so it should not happen again, but it can if Anilist is acting weird with how it handle the rate limit, sadly you can only wait and try again if this happen, I can't really do more.

**Comment by Pancakes0** [comment] 2021-03-12 14:03
yeah no worries thanks for your hard work! ヾ(＾∇＾)
