### ISSUE TITLE
[REQUEST] Sync to mangadex reading progress

### ISSUE THREAD

**Issue by Jerrk** [Glagan/SyncDex#34] opened 2021-01-21 14:18 UTC
**Is your feature request related to a problem? Please describe.**
The mangadex reading progress will only update if you change it manually, start from the beginning, or read the next chapter to the count. Say i have read 30 chapters of a manga on mangadex so the count is 30, i then read 40 chapters on a scanlators site, when i then come back to read chapter 71 on mangadex the reading progress will not update and i would have to change it manually.

**Describe the solution you'd like**
I'm not sure if this would be considered as adding another service, but i would like for the tracking count to be shown in the mangadex reading progress as well if possible.

**Additional context**
![firefox_Kt2KQN1RSW](https://user-images.githubusercontent.com/49324581/105362929-c4b44700-5bfb-11eb-8821-e1bd7cf6ce15.png)

**Comment by Glagan** [comment] 2021-01-21 19:06
Hum, adding this as a service might make some things simple, but I'm not sure (code wise).

I don't know how to avoid excessive requests thought, since I can't access this value outside of the Title page, so in all other pages that can update your list I would always send a request to update it, but in the end it's the same for all other Services.

I'll look at it, and it will be linked to the other MangaDex related options, so ``Update MD list`` will update status, score and progress.  
Maybe I will add another option to avoid updating it since it's extra requests and personally I don't use the MangaDex progress at all.

**Comment by Glagan** [comment] 2021-01-24 11:56
Sorry for the delay, I added an option since ``0.2.4``, disabled by default, in the **MangaDex** category.

![image](https://user-images.githubusercontent.com/8447621/105629457-51047b00-5e43-11eb-85c5-2419c8884766.png)

Progress is only updated one way for now, meaning that the progress is only updated but never read to update SyncDex. I might add that in another release.

**Comment by Zw012d** [comment] 2021-01-29 06:13
It has a bug in current version. ex. Mangadex last reading progress is 10.1 and next chapter is 11 then after reading the reading progress in mangadex will be 11.1 instead of 11.

**Comment by Glagan** [comment] 2021-01-29 10:42
Do you have a link for the Title the bug happened ?

**Comment by Zw012d** [comment] 2021-01-29 13:14
It occurs in every manga with decimal system. Fixed by manually `Set Latest` but that will cause history disappear bug.

Steps: Ex. -1 https://mangadex.org/title/31792/mieruko-chan
1) Read Chapter 9
![Screenshot 2021-01-29 182742](https://user-images.githubusercontent.com/76645315/106278385-a6d08d00-6260-11eb-8794-c1ce8e297980.png)
2) Read Chapter 9.5
![Screenshot 2021-01-29 182829](https://user-images.githubusercontent.com/76645315/106278425-b4861280-6260-11eb-8d48-0a4eb9536184.png)
3) Read Chapter 10
![Screenshot 2021-01-29 183100](https://user-images.githubusercontent.com/76645315/106278450-b9e35d00-6260-11eb-846d-5dde6fb0911d.png)
4) Read Chapter 11
![Screenshot 2021-01-29 183149](https://user-images.githubusercontent.com/76645315/106278468-c10a6b00-6260-11eb-80b0-66497d647ad6.png)

Steps: Ex. -2 https://mangadex.org/title/31792/mieruko-chan
1) Read Chapter 14
![Screenshot 2021-01-29 183705](https://user-images.githubusercontent.com/76645315/106278855-6f161500-6261-11eb-8bb6-c5facfbb004e.png)
2) Read Chapter 14.2
![Screenshot 2021-01-29 183836](https://user-images.githubusercontent.com/76645315/106278856-70474200-6261-11eb-91a5-e34b9d0b0be0.png)
3) Read Chapter 14.5
![Screenshot 2021-01-29 183908](https://user-images.githubusercontent.com/76645315/106278858-70474200-6261-11eb-9297-736ad38ef96d.png)
4) Read Chapter 15
![Screenshot 2021-01-29 183940](https://user-images.githubusercontent.com/76645315/106278860-70dfd880-6261-11eb-96c5-d1a40d0623de.png)

**Comment by Glagan** [comment] 2021-01-29 18:34
Seems like this is an issue related to **Mangadex** rather than **SyncDex**, I sent a message to find if I'm correct.

I looked at the request I send and I never manually update to chapter ``10.5`` (for the first example), it's only when you open a chapter and when the progress is automatically updated server side (I don't update MangaDex Progress when reading, since they do it themselves).

**Comment by Glagan** [comment] 2021-01-29 21:19
This is an error in **MangaDex**, but I added a fix to avoid that and it should be good with the next version (``0.2.8``).

**Comment by Zw012d** [comment] 2021-01-30 03:44
> This is an error in **MangaDex**, but I added a fix to avoid that and it should be good with the next version (`0.2.8`).

Thanks it is now fixed 

> Seems like this is an issue related to **Mangadex** rather than **SyncDex**, I sent a message to find if I'm correct.

I see so Mangadex team also working on the fix from their end so i guess when it fixed from their end we can remove the temp fix from Syncdex.

**Comment by Jerrk** [comment] 2021-02-10 04:27
If i import a service (specifically anilist in this case) it doesn't seem like the reading progress gets updated to match that.

is that possible to fix as well?

**Comment by Glagan** [comment] 2021-02-24 01:24
@Jerrk I'm not sure to understand.

Do you want the Reading progress to be updated on Import ?  
Import a Service only update your local save.

Is there an error where the MangaDex reading progress does not get updated after an Anilist Import, or does the MangaDex export do not update the MangaDex reading progress ?

**Comment by Jerrk** [comment] 2021-02-24 05:47
> MangaDex reading progress does not get updated after an Anilist Import

i believe is the issue.

Say i have up to chapter 60 tracked on anilist but only 30 tracked on mangadex with the reading progress.
If i click "import" on the anilist service the mangadex reading progress is **not** updated until i actually navigate to the title page (which seems to indicate the reading progress gets pulled from the services on the page load, and not on the import).

Its possible i'm misunderstanding the import/4export process since there is both a "service import/export" and a general "import/export" for MMD, SD, and MD.

So what i specifically want is that service importing should update the mangadex reading progress if possible

**Comment by Glagan** [comment] 2021-02-24 10:26
It's not a bug.  
Service Import only *import* the list on a service to your *local* save and doesn't update another external service, MangaDex included.  
I can't add a MangaDex sync after any Import since it's not the expected behavior, and not everybody want to sync MangaDex after an Import.

You can manually click the MangaDex export button if you want to update the Reading Progress after an Anilist Import.

**Comment by Jerrk** [comment] 2021-02-24 10:51
okay gotcha so doing a _service import_ adds the tracking information from that service to your _local save_ - got it.
_service export_ takes all of your _local save_ tracking information and sends it to that specific service if there are matching IDs.
Since MD is not a _service_ you are unable to export your _local save_ tracking information to its reading progress.

Exporting your _local save_ to MD does **not** update the reading progress which is what my current issue is.

so the import from a service to my _local save_ works as it should.
When i then try to export my _local save_ to MD, MD's reading progress does not update with the tracking information of the _local save_ 

So the mangadex export button does not work for updating the MD reading progress from the local save

been a couple of weeks so i actually forgot what my actual issue was for a bit and i might've given you the wrong idea😂 

so what i actaully meant was the latter part of your question

> does the MangaDex export do not update the MangaDex reading progress

so the solution of  

> You can manually click the MangaDex export button if you want to update the Reading Progress after an Anilist Import

is what does **not** work 🙂

**Comment by Glagan** [comment] 2021-02-24 15:02
I was actually not checking for the progress when filtering the Titles before exporting !  
This will be fixed in the next version (``0.2.14``).

**Comment by Jerrk** [comment] 2021-02-25 05:30
it somewhat works now but there seems to be an error/getting stuck with certain titles.

![image](https://user-images.githubusercontent.com/49324581/109107478-13d92480-7732-11eb-977a-f9f44a90aa2e.png)

![image](https://user-images.githubusercontent.com/49324581/109107551-38350100-7732-11eb-8e13-af8170c340f1.png)

https://mangadex.org/title/455/my-lovely-ghost-kana

If i remove this title and run the export it will get stuck on another (H) manga/manhwa. Some titles in the "plan to read" list also get stuck.
(there is another issue i found here where if mangaupdates status is set to complete, if you remove it in your local save it does **not** update the status on mangaupdates. if the status is set to reading however - removing from local save does remove from mangaupdates. seems to be an issue where if something is set to completed on mangaupdates you need to change the staatus first to be able to remove it)

**Comment by Glagan** [comment] 2021-02-25 11:45
Seems like I missed something in the MangaDex API documentation, some titles (all "H" titles) were missing in the returned list endpoints, I added them.  
I also missed a check if the title wasn't already in your MangaDex list, it should be fine now.

It's another probably unrelated issue for MangaUpdates but I'll look at it.

**Comment by Glagan** [comment] 2021-02-25 15:31
The MangaUpdates error will be fixed in version ``0.2.15``.

Open another issue if you have another bug not related to the MangaDex progress.

**Closed as completed by Glagan** 2021-02-25 15:31 UTC
Labels: enhancement
